---
driver:
  name: vagrant
#  synced_folders: 
#    - ["/var/www/work/my/PGD/pgd_1.4/vagrant/pgd", "/home/vagrant/pgd"]

attributes:
    pgd:
        pgd_path: '/home/vagrant/pgd'
        virtualenv_path: '/home/vagrant/vrt'
        user: 'vagrant'
        group: 'vagrant'

provisioner:
  name: chef_solo
  data_bags_path: test/integration/data_bags
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  require_chef_omnbus: 11.8.0

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[pgd_cookbook::default]
      - recipe[pgd_cookbook::bootstrap_user]
