---
driver:
  name: vagrant
#  synced_folders: 
#    - ["/var/www/work/my/PGD/pgd_1.4/vagrant/pgd", "/home/vagrant/pgd"]

provisioner:
  name: chef_solo
  require_chef_omnibus: 11.12.8
  data_bags_path: test/integration/data_bags/
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret

platforms:
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[pgd_cookbook::default]
      - recipe[pgd_cookbook::bootstrap_user]
